# Generated by Django 5.0.4 on 2024-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=64)),
                ('tytul', models.CharField(max_length=256)),
                ('opis', models.CharField(max_length=256)),
                ('stan', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
