# Generated by Django 5.0.4 on 2024-05-09 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wypozyczone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzytkownik', models.CharField(blank=True, max_length=32)),
                ('autor', models.CharField(blank=True, max_length=64)),
                ('tytul', models.CharField(blank=True, max_length=256)),
                ('opis', models.CharField(blank=True, max_length=256)),
                ('datawypoz', models.DateField(default=datetime.date.today)),
                ('czyoddane', models.BooleanField(default=False)),
                ('ulubione', models.BooleanField(default=False)),
                ('notatki', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
